name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  security:
    uses: rahulreddy0120/gh-reusable-workflow-templates/.github/workflows/sast-dast-scan.yml@main
    with:
      language: python
      sast_enabled: true
      dependency_scan: true
      secret_scan: true

  tag-audit:
    if: github.ref == 'refs/heads/main'
    uses: rahulreddy0120/gh-reusable-workflow-templates/.github/workflows/aws-tag-compliance.yml@main
    with:
      role_arn: ${{ vars.AWS_READONLY_ROLE_ARN }}
      enforce: false
